macro(bunsan_required_arguments prefix)
    foreach(arg ${ARGN})
        if(NOT DEFINED ${prefix}_${arg})
            message(SEND_ERROR "Must set ${arg}")
        endif()
    endforeach()
endmacro()

macro(bunsan_required_variables)
    foreach(var ${ARGN})
        if(NOT DEFINED ${var})
            message(SEND_ERROR "Must set ${var}")
        endif()
    endforeach()
endmacro()

macro(bunsan_list_remove_duplicates var)
    list(LENGTH ${var} bunsan_list_remove_duplicates_length)
    if(bunsan_list_remove_duplicates_length GREATER 0)
        list(REMOVE_DUPLICATES ${var})
    endif()
endmacro()

macro(bunsan_unset)
    foreach(arg ${ARGN})
        unset(${arg})
        unset(${arg} CACHE)
    endforeach()
endmacro()
