macro(bunsan_required_arguments prefix)
    foreach(arg ${ARGN})
        if(NOT DEFINED ${prefix}_${arg})
            message(SEND_ERROR "Must set ${arg}")
        endif()
    endforeach()
endmacro()

macro(bunsan_required_variables)
    foreach(var ${ARGN})
        if(NOT DEFINED ${var})
            message(SEND_ERROR "Must set ${var}")
        endif()
    endforeach()
endmacro()
